-- MySQL Script generated by MySQL Workbench
-- Sat Nov 11 14:38:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library` DEFAULT CHARACTER SET utf8;
USE `library`;
-- -----------------------------------------------------
-- Table `library`.`authors`
-- -----------------------------------------------------
DROP 
  TABLE IF EXISTS `library`.`authors`;
CREATE TABLE IF NOT EXISTS `library`.`authors` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT, 
  `name` VARCHAR(45) NOT NULL, 
  PRIMARY KEY (`id`), 
  UNIQUE INDEX `id_UNIQUE` (`id` ASC), 
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)
) ENGINE = InnoDB;
INSERT INTO `library`.`authors` (`name`) 
VALUES 
  ('Charles Dickens'), 
  ('William Shakespeare'), 
  ('Agatha Christie'), 
  ('J. K. Rowling');
-- -----------------------------------------------------
-- Table `library`.`books`
-- -----------------------------------------------------
DROP 
  TABLE IF EXISTS `library`.`books`;
CREATE TABLE IF NOT EXISTS `library`.`books` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT, 
  `title` VARCHAR(50) NOT NULL, 
  `isbn` VARCHAR(20) NOT NULL, 
  `shelf` VARCHAR(5) NOT NULL, 
  `quantity` INT UNSIGNED NOT NULL DEFAULT 0, 
  `author_id` INT UNSIGNED NOT NULL, 
  PRIMARY KEY (`id`), 
  UNIQUE INDEX `title_UNIQUE` (`title` ASC), 
  UNIQUE INDEX `isbn_UNIQUE` (`isbn` ASC), 
  CONSTRAINT `author_id` FOREIGN KEY (`author_id`) REFERENCES `library`.`authors` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;
INSERT INTO `library`.`books` (
  `title`, `isbn`, `shelf`, `quantity`, 
  `author_id`
) 
VALUES 
  (
    'A Christmas Carol', 
    '1111', 
    'AB', 
    5, 
    (
      SELECT 
        `id` 
      FROM 
        `library`.`authors` 
      WHERE 
        `name` = 'Charles Dickens'
    )
  ), 
  (
    'Romeo and Juliet', 
    '2222', 
    'AB', 
    5, 
    (
      SELECT 
        `id` 
      FROM 
        `library`.`authors` 
      WHERE 
        `name` = 'William Shakespeare'
    )
  ), 
  (
    'And Then There Were None', 
    '3333', 
    'AB', 
    5, 
    (
      SELECT 
        `id` 
      FROM 
        `library`.`authors` 
      WHERE 
        `name` = 'Agatha Christie'
    )
  ), 
  (
    'Harry Potter', 
    '4444', 
    'AB', 
    5, 
    (
      SELECT 
        `id` 
      FROM 
        `library`.`authors` 
      WHERE 
        `name` = 'J. K. Rowling'
    )
  );
-- -----------------------------------------------------
-- Table `library`.`members`
-- -----------------------------------------------------
DROP 
  TABLE IF EXISTS `library`.`members`;
CREATE TABLE IF NOT EXISTS `library`.`members` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT, 
  `name` VARCHAR(45) NOT NULL, 
  `email` VARCHAR(45) NULL, 
  `phone` VARCHAR(20) NULL, 
  `registration_date` DATE NOT NULL, 
  PRIMARY KEY (`id`), 
  UNIQUE INDEX `email_UNIQUE` (`email` ASC), 
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC)
) ENGINE = InnoDB;
INSERT INTO `library`.`members` (
  `name`, `email`, `phone`, `registration_date`
) 
VALUES 
  (
    'Rogina Romany', 'email@bosta.co', 
    NULL, DATE '2023-10-11'
  ), 
  (
    'Mohammed Deifallah', NULL, '+20', 
    DATE '2023-10-10'
  ), 
  (
    'Ahmed Khateeb', 'email2@bosta.co', 
    NULL, DATE '2023-10-10'
  ), 
  (
    'Mohamed Galal', 'email3@bosta.co', 
    NULL, DATE '2023-10-09'
  );


-- -----------------------------------------------------
-- Table `library`.`borrowings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library`.`borrowings` ;

CREATE TABLE IF NOT EXISTS `library`.`borrowings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `book_id` INT UNSIGNED NOT NULL,
  `member_id` INT UNSIGNED NOT NULL,
  `start_date` DATE NOT NULL,
  `due_date` DATE NOT NULL,
  `done` TINYINT(1) UNSIGNED ZEROFILL NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `book_id_idx` (`book_id` ASC),
  INDEX `member_id_idx` (`member_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `book_id`
    FOREIGN KEY (`book_id`)
    REFERENCES `library`.`books` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `member_id`
    FOREIGN KEY (`member_id`)
    REFERENCES `library`.`members` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
